model:
  in_channels: 10
  base_channels: 64
  time_emb_dim: 128
  depth: 5
  diffusion_steps: 1000
  beta_start: 0.0001
  beta_end: 0.02

train:

  embedding_dim: 16
  batch_size: 4
  learning_rate: 0.0001
  epochs: 200
  print_every: 30
  val_split: 0.1
